### ISSUE TITLE
[BUG] Not runnig anymore...

### ISSUE THREAD

**Issue by mi-khatri** [HanzHaxors/fabuya#8]
hello,
i tried to install and run repository, but there is no success for me.

all of my try is fail, my error is below...

F:\Web_Development\Website_Projects\fabuya_MD>node app.js
F:\Web_Development\Website_Projects\fabuya_MD\node_modules\fabuya\index.js:106
        #bindEvents() {
                   ^

SyntaxError: Unexpected token '('
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (F:\Web_Development\Website_Projects\fabuya_MD\app.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

please help ...

**Comment by HanzCEO** [comment]
Can you tell me your NodeJS version?

**Comment by HanzCEO** [comment]
I will fallback to calling _unexported_ function instead

**Comment by mi-khatri** [comment]
> Can you tell me your NodeJS version?

v12.22.1

**Comment by HanzCEO** [comment]
The problem has been fixed in `v0.1.0-nightly.1` kindly upgrade using `npm install fabuya@nightly`

**Comment by mi-khatri** [comment]
hello, i tried nightly version but no luck...
error is ...

F:\Web_Development\Website_Projects\fabuya_MD\node_modules\fabuya\index.js:131               
                                let statusCode = lastDisconnect.error?.output?.statusCode;   
                                                                      ^                      
                                                                                             
SyntaxError: Unexpected token '.'                                                            
    at wrapSafe (internal/modules/cjs/loader.js:915:16)                                      
    at Module._compile (internal/modules/cjs/loader.js:963:27)                               
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)                
    at Module.load (internal/modules/cjs/loader.js:863:32)                                   
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)                         
    at Module.require (internal/modules/cjs/loader.js:887:19)                                
    at require (internal/modules/cjs/helpers.js:74:18)                                       
    at Object.<anonymous> (F:\Web_Development\Website_Projects\fabuya_MD\app.js:1:16)        
    at Module._compile (internal/modules/cjs/loader.js:999:30)                               
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)                

please help

**Comment by HanzCEO** [comment]
Well, it seems that your node js version cannot satisfy the requirement of
this package.

I will resolve this issue today

**Comment by HanzCEO** [comment]
Kingly upgrade to `v0.1.0-nightly.2`, i already fixed the problem. Open a new issue if you have another problem.

Thank you
